# Домашнее задание к лекции "Функции"

Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

1. перечень всех документов
```
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
```
2. перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)
```
directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}
```

Общие требования к программе:
- код должен быть грамотно декомпозирован (каждая функция отвечает за свою конкретную задачу, дублирующийся функционал переиспользуется, а его код не повторяется);
- в коде отсутствуют глобальные переменные (за исключением **documents** и **directories**);
- пользовательский ввод обрабатывается в цикле **while** до тех пор, пока пользователь явно не завершит программу (вводом команды "**q**").

## Задание 1

### Пункт 1. Пользователь по команде "*p*" может узнать владельца документа по его номеру

Примеры работы:

1.

```
Введите команду:
p

Введите номер документа:
10006
```
Результат:  
`Владелец документа: Аристарх Павлов`

2.
```
Введите команду:
p

Введите номер документа:
12345
```
Результат:  
`Документ не найден в базе`

### Пункт 2. Пользователь по команде "*s*" может по номеру документа узнать на какой полке он хранится

Примеры работы:

1.

```
Введите команду:
s

Введите номер документа:
10006
```
Результат:  
`Документ хранится на полке: 2`

2.
```
Введите команду:
p

Введите номер документа:
12345
```
Результат:  
`Документ не найден в базе`

### Пункт 3. Пользователь по команде "*l*" может увидеть полную информацию по всем документам

Пример работы:

```
Введите команду:
l
```

Результат:  
```
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

### Пункт 4. Пользователь по команде "*ads*" может добавить новую полку

Примеры работы:

1.

```
Введите команду:
ads

Введите номер полки:
10
```
Результат:  
`Полка добавлена. Текущий перечень полок: 1, 2, 3, 10.`

2.
```
Введите команду:
ads

Введите номер полки:
1
```
Результат:  
`Такая полка уже существует. Текущий перечень полок: 1, 2, 3.`

### Пункт 5. Пользователь по команде "*ds*" может удалить существующую полку из данных (только если она пустая)

Примеры работы:

1.

```
Введите команду:
ds

Введите номер полки:
3
```
Результат:  
`Полка удалена. Текущий перечень полок: 1, 2.`

2.
```
Введите команду:
ds

Введите номер полки:
1
```
Результат:  
`На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3.`

3.
```
Введите команду:
ds

Введите номер полки:
4
```
Результат:  
`Такой полки не существует. Текущий перечень полок: 1, 2, 3.`

In [1]:
documents = [
 {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
 {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
 {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
directories = {
 '1': ['2207 876234', '11-2'],
 '2': ['10006'],
 '3': []
}

In [2]:
def make_dict(documents):
    p_documents = { x['number'] : {'name': x['name'], 'type': x['type']} for x in documents }
    for key, value in directories.items():
        for i in range(len(value)):
            p_documents[value[i]]['directory'] = key
    return p_documents

def list_directories():
    output = 'Текущий перечень полок: '
    for key in directories.keys():
        output += key + ', '
    return output[:-2]

def find_owner():
    p_documents = make_dict(documents)
    number = input('Введите номер документа: ')    
    if number in p_documents.keys():
        return 'Владелец документа: ' + p_documents[number]['name']
    else:
        return 'Документ не найден в базе'
    
def search():
    p_documents = make_dict(documents)
    number = input('Введите номер документа: ')
    if number in p_documents.keys():
            return 'Документ находится на полке: ' + p_documents[number]['directory']
    return 'Документ не найден в базе'

def list_docs():
    p_documents = make_dict(documents)
    output = ''
    for key, value in p_documents.items():
        output += '№: {0}, тип: {1}, владелец: {2}, полка хранения: {3}\r\n'.format(key, value['type'], value['name'], value['directory'])
    return output

def add_dir():
    number = input('Введите номер полки: ')
    if not number in directories.keys():
        directories[number] = []
        return 'Полка добавлена. ' + list_directories()
    else:
        return 'Такая полка уже существует. ' + list_directories()
    
def del_dir():
    number = input('Введите номер полки: ')
    if number in directories.keys():
        if len(directories[number]) == 0:
            directories.pop(number)
            return 'Полка удалена. ' + list_directories()
        else:
            return 'На полке есть документы, удалите их перед удалением полки. ' + list_directories()
    else:
        return 'Такой полки не существует. ' + list_directories()

## Задание 2 (необязательное)

Вам необходимо дополнить программу из задания 1 более продвинутыми командами.

### Пункт 1. Пользователь по команде "*ad*" может добавить новый документ в данные

Примеры работы:

1.

```
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
3
```
Результат:  
```
Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3
```

2.
```
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
4
```
Результат:  
```
Такой полки не существует. Добавьте полку командой as. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

### Пункт 2. Пользователь по команде "*d*" может удалить документ из данных

Примеры работы:

1.

```
Введите команду:
d

Введите номер документа:
10006
```
Результат:  
```
Документ удален. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
```

2.
```
Введите команду:
d

Введите номер документа:
123456
```
Результат:  
```
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

### Пункт 3. Пользователь по команде "*m*" может переместить документ с полки на полку

Примеры работы:

1.

```
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
3
```
Результат:  
```
Документ перемещен. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 3
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

2.
```
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
10
```
Результат:  
`Такой полки не существует. Текущий перечень полок: 1, 2, 3.`

3.
```
Введите команду:
m

Введите номер документа:
42
Введите номер полки:
2
```
Результат:  
```
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

In [3]:
def add_doc():
    number = input('Введите номер документа: ')
    doctype = input('Введите тип документа: ')
    name = input('Введите владельца документа: ')
    directory = input('Введите полку для хранения: ')
    p_documents = make_dict(documents)
    if directory in directories.keys():
        if number not in p_documents.keys():
            documents.append({ 'name' : name, 'type' : doctype, 'number' : number })
            directories[directory].append(number)
            return 'Документ добавлен. Текущий список документов:\r\n' + list_docs()
        else:
            return 'Документ с таким номером уже существует. Текущий список документов:\r\n' + list_docs()
    else:
        return 'Такой полки не существует. Добавьте полку командой ads. Текущий список документов:\r\n' + list_docs()

def del_doc():
    number = input('Введите номер документа: ')
    p_documents = make_dict(documents)
    if number in p_documents.keys():
        directories[p_documents[number]['directory']].remove(number)
        for i in range(len(documents)):
            if documents[i]['number'] == number:
                documents.pop(i)
        return 'Документ удалён.\r\nТекущий Список документов в базе:\r\n' + list_docs()
    else:
        return 'Документ не найден в базе. Текущий список документов:\r\n' + list_docs()

def move_doc():
    number = input('Введите номер документа: ')
    new_dir = input('Введите номер полки: ')
    p_documents = make_dict(documents)
    if number in p_documents.keys():
        if new_dir in directories.keys():
            directories[new_dir].append(number)
            directories[p_documents[number]['directory']].remove(number)
            return 'Документ перенесён.\r\nТекущий список документов:\r\n' + list_docs()
        else:
            return 'Такой полки не существует. ' + list_directories()
    else:
        'Документ не найден в базе.\r\nТекущий список документов:\r\n' + list_docs()

In [4]:
def com(command):
    if command == 'p':
        print(find_owner())
    elif command == 's':
        print(search())
    elif command == 'l':
        print(list_docs())
    elif command == 'ads':
        print(add_dir())
    elif command == 'ds':
        print(del_dir())
    elif command == 'ad':
        print(add_doc())
    elif command == 'd':
        print(del_doc())
    elif command == 'm':
        print(move_doc())

command = ''
while command != 'q':
    command = input('Введите команду: ')
    com(command)

Введите команду: ad
Введите номер документа: 1
Введите тип документа: test
Введите владельца документа: owner
Введите полку для хранения: 1
Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 1, тип: test, владелец: owner, полка хранения: 1

Введите команду: ads
Введите номер полки: 4
Полка добавлена. Текущий перечень полок: 1, 2, 3, 4
Введите команду: l
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 1, тип: test, владелец: owner, полка хранения: 1

Введите команду: m
Введите номер документа: 1
Введите номер полки: 4
Документ перенесён.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Ва

Александр, здравствуйте!

Спасибо за работу, функционально почти все выполнено верно.

Есть ряд моментов, которые стоит поправить:

на данный момент команда ad у вас не добавляет документы в исходную структуру данных (documents):
```
Введите команду: ad
Введите номер документа: 11
Введите тип документа: 11
Введите владельца документа: 11
Введите полку для хранения: 1
Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 11, тип: 11, владелец: 11, полка хранения: 1

[{'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'}, {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'}, {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}]
{'1': ['2207 876234', '11-2', '11'], '2': ['10006'], '9': []}
```

аналогично с удалением;
в условии приведены именно пользовательские команды, сами функции стоит именовать более полноценно и значимо;
в коде не вообще не должно быть глобальных переменных (кроме исходных данных). И финальный блок кода с обработкой пользовательского ввода лучше поместить в отдельную функцию.
Просьба это поправить :)

#### ПРИМЕЧАНИЕ
Домашнее задание сдается ссылкой на репозиторий [GitHub](https://github.com/).
Не сможем проверить или помочь, если вы пришлете:
- файлы;
- архивы;
- скриншоты кода.

Все обсуждения и консультации по выполнению домашнего задания ведутся только на соответствующем канале в slack.

##### Как правильно задавать вопросы аспирантам, преподавателям и коллегам
Прежде чем задать вопрос, попробуйте найти ответ в интернете. Навык самостоятельного поиска информации — один из важнейших. Каждый практикующий специалист любого уровня делает это ежедневно.

Сформулируйте вопрос по алгоритму:  
1) Что я делаю?  
2) Какого результата я ожидаю?  
3) Как фактический результат отличается от ожидаемого?  
4) Что я уже попробовал сделать, чтобы исправить проблему?  

По возможности прикрепите к вопросу скриншоты либо ссылки на код. Не выкладывайте все решение, оставляйте только проблемный и воспроизводимый участок кода.